import { test, expect } from '@playwright/test'
import { validSaId } from './helpers/said'
async function ensureAdmin(request: any, email: string, role: string, zoneId?: string, schoolId?: string) {
  const tokenRes = await request.post('http://localhost:4000/api/login', { data: { role: 'EPHSRUAdmin' }, headers: { 'Content-Type': 'application/json' } })
  const { token } = await tokenRes.json()
  await request.post('http://localhost:4000/api/admins', { data: { name: 'E2E', surname: 'Admin', email, role, zoneId, schoolId }, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` } })
}
async function ensureCoach(request: any, email: string, zoneId: string, schoolId: string) {
  const tokenRes = await request.post('http://localhost:4000/api/login', { data: { role: 'SchoolAdmin', zoneId, schoolId }, headers: { 'Content-Type': 'application/json' } })
  const { token } = await tokenRes.json()
  await request.post('http://localhost:4000/api/coaches', { data: { name: 'E2E', surname: 'Coach', zoneId, schoolId, email }, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` } })
}

test('Home renders and navigates to School form', async ({ page }) => {
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  await expect(page.getByText('EPHSRU Rugby Portal')).toBeVisible()
  const registerSection = page.locator('section:has(h1:has-text("Register"))')
  await registerSection.getByLabel('Email').fill(`e2e.school.${Date.now()}@example.com`)
  await registerSection.getByLabel('Create Password').fill('secret123')
  await registerSection.getByLabel('Verify Password').fill('secret123')
  await registerSection.getByLabel('Select registration form').selectOption({ value: 'school' })
  await registerSection.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').waitFor()
  await page.getByTestId('zone-select').selectOption({ index: 1 })
  await page.getByTestId('school-select').waitFor()
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await expect(page.getByText('Pool')).toBeVisible()
})

test('Player age suggestions and submission', async ({ page }) => {
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const registerSection = page.locator('section:has(h1:has-text("Register"))')
  await registerSection.getByLabel('Email').fill(`e2e.player.${Date.now()}@example.com`)
  await registerSection.getByLabel('Create Password').fill('secret123')
  await registerSection.getByLabel('Verify Password').fill('secret123')
  await registerSection.getByLabel('Select registration form').selectOption({ value: 'player' })
  await registerSection.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').waitFor()
  await page.getByTestId('zone-select').selectOption({ index: 1 })
  await page.getByTestId('school-select').waitFor()
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await page.getByLabel('Date of Birth').fill('2010-05-10')
  await page.getByLabel('Gender').selectOption({ label: 'Female' })
  await page.getByLabel('ID/Passport').fill(validSaId(Date.now(), '2010-05-10', 'Female'))
  await expect(page.getByText('Eligible Age Groups')).toBeVisible()
  await expect(page.getByLabel('Age Group (auto-suggested)')).toBeVisible()
  await page.getByLabel('POPIA consent').check()
  await page.getByRole('button', { name: 'Submit Player Registration' }).click()
  await expect(page.getByText(/Congratulations! Your player registration has been submitted/i)).toBeVisible()
})

test('Dashboard shows records after submissions', async ({ page, request }) => {
  const email = `e2e.admin.${Date.now()}@example.com`
  await ensureAdmin(request, email, 'SchoolAdmin', '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await page.getByTestId('btn-dashboard').click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
})

test('Login as EPHSRUAdmin shows audit logs', async ({ page, request }) => {
  const email = `e2e.super.${Date.now()}@example.com`
  await ensureAdmin(request, email, 'EPHSRUAdmin')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  await page.goto('http://localhost:5173/')
  await expect(page.getByText('Audit Logs')).toBeVisible()
})
test('Coach submits player and sees on dashboard', async ({ page, request }) => {
  const email = `e2e.coach.${Date.now()}@example.com`
  await ensureCoach(request, email, '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  await page.goto('http://localhost:5173/')
  const registerSection = page.locator('section:has(h1:has-text("Register"))')
  await registerSection.getByLabel('Email').fill(`e2e.player.${Date.now()}@example.com`)
  await registerSection.getByLabel('Create Password').fill('secret123')
  await registerSection.getByLabel('Verify Password').fill('secret123')
  await registerSection.getByLabel('Select registration form').selectOption({ value: 'player' })
  await registerSection.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').selectOption({ index: 1 })
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Test')
  await page.getByRole('textbox', { name: 'Surname', exact: true }).fill('Player')
  await page.getByLabel('ID/Passport').fill(validSaId(Date.now(), '2010-01-01', 'Male'))
  await page.getByLabel('Date of Birth').fill('2010-01-01')
  await page.getByLabel('Gender').selectOption({ label: 'Male' })
  await page.getByLabel('POPIA consent').check()
  page.once('dialog', (d) => d.accept())
  await page.getByRole('button', { name: 'Submit Player Registration' }).click()
  await page.getByRole('button', { name: 'View Player Dashboard' }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
})
test('Approvals page loads for SchoolAdmin role', async ({ page, request }) => {
  const email = `e2e.schooladmin.${Date.now()}@example.com`
  await ensureAdmin(request, email, 'SchoolAdmin', '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await page.getByTestId('btn-dashboard').click()
  await page.getByTestId('btn-approvals').click()
  await page.waitForSelector('h1:text("Approvals")')
  await expect(page.locator('h1').filter({ hasText: 'Approvals' }).first()).toBeVisible()
})
test('Nav gating hides Approvals and Reports for Coach', async ({ page, request }) => {
  const email = `e2e.coach.${Date.now()}@example.com`
  await ensureCoach(request, email, '1', 'S1')
  await page.goto('/')
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await page.goto('http://localhost:5173/')
  await expect(page.getByTestId('btn-approvals')).toHaveCount(0)
  await expect(page.getByTestId('btn-reports')).toHaveCount(0)
})

test('Nav gating shows Approvals for SchoolAdmin and Reports for ZoneCoordinator', async ({ page, request }) => {
  const email1 = `e2e.schooladmin.${Date.now()}@example.com`
  const email2 = `e2e.zone.${Date.now()}@example.com`
  await ensureAdmin(request, email1, 'SchoolAdmin', '1', 'S1')
  await ensureAdmin(request, email2, 'ZoneCoordinator')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email1)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await page.getByTestId('btn-dashboard').click()
  await expect(page.getByTestId('btn-approvals')).toBeVisible()
  await expect(page.getByTestId('btn-reports')).toHaveCount(0)
  await page.getByTestId('btn-login').click()
  const loginForm2 = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm2.getByLabel('Email').fill(email2)
  await loginForm2.getByLabel('Password').fill('secret123')
  await loginForm2.getByRole('button', { name: 'Sign In' }).click()
  await page.getByTestId('btn-dashboard').click()
  await expect(page.getByTestId('btn-reports')).toBeVisible()
})
test.skip('Unauthorized navigation blocked for Coach to School registration (no button)', async () => {})

test('SchoolAdmin can submit school registration with updated information', async ({ page, request }) => {
  const email = `e2e.schooladmin.${Date.now()}@example.com`
  await ensureAdmin(request, email, 'SchoolAdmin', '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  await page.goto('http://localhost:5173/')
  const registerSection2 = page.locator('section:has(h1:has-text("Register"))')
  await registerSection2.getByLabel('Email').fill(`e2e.school.${Date.now()}@example.com`)
  await registerSection2.getByLabel('Create Password').fill('secret123')
  await registerSection2.getByLabel('Verify Password').fill('secret123')
  await registerSection2.getByLabel('Select registration form').selectOption({ value: 'school' })
  await registerSection2.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').selectOption({ index: 1 })
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await page.getByLabel('School Physical Address').fill('123 Updated Street')
  await page.getByLabel('School Contact Number').fill('0821234567')
  await page.getByLabel('School Email Address').fill('updated@school.co.za')
  await page.getByRole('button', { name: 'Submit School Registration' }).click()
  await expect(page.getByText(/CONGRATULATIONS !!!/i)).toBeVisible()
})

test('Coach can submit player registration with updated information', async ({ page, request }) => {
  const email = `e2e.coach.${Date.now()}@example.com`
  await ensureCoach(request, email, '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  await page.goto('http://localhost:5173/')
  const registerSection3 = page.locator('section:has(h1:has-text("Register"))')
  await registerSection3.getByLabel('Email').fill(`e2e.player.${Date.now()}@example.com`)
  await registerSection3.getByLabel('Create Password').fill('secret123')
  await registerSection3.getByLabel('Verify Password').fill('secret123')
  await registerSection3.getByLabel('Select registration form').selectOption({ value: 'player' })
  await registerSection3.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').selectOption({ index: 1 })
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Test Player')
  await page.getByRole('textbox', { name: 'Surname', exact: true }).fill('Update Test')
  await page.getByLabel('ID/Passport').fill(validSaId(Date.now(), '2010-01-01', 'Male'))
  await page.getByLabel('Date of Birth').fill('2010-01-01')
  await page.getByLabel('Gender').selectOption({ label: 'Male' })
  await page.getByLabel('POPIA consent').check()
  await page.getByRole('button', { name: 'Submit Player Registration' }).click()
  await expect(page.getByText(/Congratulations! Your player registration has been submitted/i)).toBeVisible()
})

test('SchoolAdmin cannot submit school registration outside their scope', async ({ page, request }) => {
  const email = `e2e.schooladmin.${Date.now()}@example.com`
  await ensureAdmin(request, email, 'SchoolAdmin', '1', 'S1')
  await page.goto('http://localhost:5173/')
  await page.evaluate(() => { try { localStorage.removeItem('nav:target') } catch {} })
  const loginForm = page.locator('form:has(button:has-text("Sign In"))')
  await loginForm.getByLabel('Email').fill(email)
  await loginForm.getByLabel('Password').fill('secret123')
  await loginForm.getByRole('button', { name: 'Sign In' }).click()
  await page.getByTestId('btn-home').click()
  const registerSection4 = page.locator('section:has(h1:has-text("Register"))')
  await registerSection4.getByLabel('Email').fill(`e2e.school.${Date.now()}@example.com`)
  await registerSection4.getByLabel('Create Password').fill('secret123')
  await registerSection4.getByLabel('Verify Password').fill('secret123')
  await registerSection4.getByLabel('Select registration form').selectOption({ value: 'school' })
  await registerSection4.getByRole('button', { name: 'Continue' }).click()
  await page.getByTestId('zone-select').selectOption({ index: 2 })
  await page.getByTestId('school-select').selectOption({ index: 1 })
  await page.getByLabel('School Physical Address').fill('123 Unauthorized Street')
  await page.getByRole('button', { name: 'Submit School Registration' }).click()
  await page.waitForTimeout(1000)
})
